### ISSUE TITLE
Include more global (non-US) issuers on Participating Issuer page.

### ISSUE THREAD

**Issue by ottonomy** [IMSGlobal/openbadges.org-static#7]
Thanks @dajbelshaw for reviewing #5 (FYI @ccrytzer). Indeed we do not have a representative listing of projects on the Participating Issuers page. [See draft here](http://openbadges.github.io/openbadges.org-static/about/participating-issuers/). 

I'll leave this ticket open until 23 June and publicize it from various Open Badges channels. Let's look through http://www.badgetheworld.org/ and elsewhere to add some good use cases for Open Badges that better represent our community's global reach. Leave suggestions in the comments here for what should be added, and we'll construct a pull request with them all here. Additionally, if there are some in the draft list that are out of date, feel free to comment on that.

If you're suggesting a project to be added, please also let us know if you are a representative of that project who can speak for it.

Template for suggesting a new addition (advanced users: wrap in back-ticks to make it easier for us to copy and paste):

``` markdown
* [Project Name](https://projecthomepage.org/home)
```

**Comment by nercas** [comment]
[Badgecraft](https://www.badgecraft.eu/en/use-cases)
[European Badge Alliance](http://ebawebsite.net/)

**Comment by ottonomy** [comment]
@nercas Is BadgeCraft itself an issuer, awarding badges under its own name? It does appear as a platform already in the draft [here](http://openbadges.github.io/openbadges.org-static/about/participating-services/#Badgecraft). Should it also appear in this list?

Is EBA the issuer of record for the badges appearing on that website? Or is it more a site that lists other projects that we should include in this list individually?

**Comment by nercas** [comment]
@ottonomy thanks for asking to clarify. Badgecraft is issuing badges during various promo events and big activities, such as forums, conferences, workshops.

EBA is the umbrella project that unites organisations and projects which promote and use badges for European mobility project. If you would like to list every single project that will use ready-made badges systems for mobility, it may become an endless list.
In any case, any of your decision to include or not both references are welcomed. We try to bring in non-U.S. examples of badge projects.
